const paletaDeCores = document.getElementById('color-palette');
const coresDaPaleta1 = document.createElement('div');
const coresDaPaleta2 = document.createElement('div');
const coresDaPaleta3 = document.createElement('div');
const coresDaPaleta4 = document.createElement('div');
coresDaPaleta1.setAttribute('class', 'color');
coresDaPaleta2.setAttribute('class', 'color');
coresDaPaleta3.setAttribute('class', 'color');
coresDaPaleta4.setAttribute('class', 'color');
coresDaPaleta1.setAttribute('id', 'corPreta');
coresDaPaleta2.setAttribute('id', 'corVermelha');
coresDaPaleta3.setAttribute('id', 'corAzul');
coresDaPaleta4.setAttribute('id', 'corVerde');
paletaDeCores.appendChild(coresDaPaleta1); paletaDeCores.appendChild(coresDaPaleta2); paletaDeCores.appendChild(coresDaPaleta3); paletaDeCores.appendChild(coresDaPaleta4);
